pci-latency: Replace sudo with root checks
This speeds up startup of the systemd service from 40ms -> 18ms

diff --git a/usr/bin/pci-latency b/usr/bin/pci-latency
--- a/usr/bin/pci-latency
+++ b/usr/bin/pci-latency
@@ -6,7 +6,11 @@
 # devices, which can help prevent devices with high default latency timers from
 # causing gaps in sound.
 
-sudo -s -- <<EOF
+# Check if the script is run with root privileges
+if [ "$(id -u)" -ne 0 ]; then
+  echo "Error: This script must be run with root privileges."
+  exit 1
+fi
 
 # Reset the latency timer for all PCI devices
 setpci -v -s '*:*' latency_timer=20
@@ -14,4 +18,3 @@ setpci -v -s '0:0' latency_timer=0
 
 # Set latency timer for all sound cards
 setpci -v -d "*:*:04xx" latency_timer=80
-EOF
