Some style nits
Signed-off-by: Vasiliy Stelmachenok <ventureo@cachyos.org>

diff --git a/usr/bin/pci-latency b/usr/bin/pci-latency
--- a/usr/bin/pci-latency
+++ b/usr/bin/pci-latency
@@ -1,5 +1,4 @@
-#!/bin/sh
-
+#!/usr/bin/env sh
 # This script is designed to improve the performance and reduce audio latency
 # for sound cards by setting the PCI latency timer to an optimal value of 80
 # cycles. It also resets the default value of the latency timer for other PCI
@@ -8,7 +7,7 @@
 
 # Check if the script is run with root privileges
 if [ "$(id -u)" -ne 0 ]; then
-  echo "Error: This script must be run with root privileges."
+  echo "Error: This script must be run with root privileges." >&2
   exit 1
 fi
 
