sbctl-batch-sign: Make indentations consistent
Signed-off-by: Eric Naim <dnaim@cachyos.org>

diff --git a/usr/bin/sbctl-batch-sign b/usr/bin/sbctl-batch-sign
--- a/usr/bin/sbctl-batch-sign
+++ b/usr/bin/sbctl-batch-sign
@@ -11,8 +11,8 @@ if [ -f /boot/limine.conf ]; then
 fi
 
 if [ "$(id -u)" -ne 0 ]; then
-  echo "Error: This script must be run with root privileges."
-  exit 1
+    echo "Error: This script must be run with root privileges."
+    exit 1
 fi
 
 if [ "$#" -eq 0 ]; then
